version: 0.2

# http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide//VPC_Scenario2.html

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - make build
  post_build:
    commands:
      - make tag
      - make push
      - printf '[{"name":"dragon-api","imageUri":"%s"}]' 957774660254.dkr.ecr.us-west-2.amazonaws.com/dragon-api:$(cat ./version.cfg) > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
