version: '3'

services:

  ##
  ##  Warehouse
  ##
  api:
    build:
      context: .
    image: dragon-api
    env_file: .env
    restart: always
    volumes:
      - .:/usr/src/dragon-api
      - ~/.aws:/root/.aws
    ports:
      - "5000:5000"
    command: python -u src/api.py
    healthcheck:
      test: curl --fail http://localhost:5000/api/ping || exit 1
    links:
      - dynamo:dynamo
    depends_on:
      - dynamo


  ##
  ##  Database
  ##
  dynamo:
    image: tutum/dynamodb:latest
    ports:
      - "8000:8000"
    hostname: dynamo

  dynamo_init:
    env_file: .env
    depends_on:
      - dynamo
    links:
      - dynamo:dynamo
    image: dragon-api
    volumes:
      - .:/usr/src/dragon-api
      - ~/.aws:/root/.aws
    command: make -f Makefile.targets dynamo-setup
    restart: 'no'
