

.PHONY: lint
lint:
	pylint ./src

.PHONY: test-unit
test-unit:
	py.test --color=yes --cov-report html --cov-report term --cov=src test/unit --cov-fail-under=80

.PHONY: dynamo-setup
dynamo-setup:
	python -u /usr/src/dragon/db/create_tables.py
